spring:
  application:
    name: SportTracker
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/sport-tracker-db
    username: postgres
    password: user